# Discuss status codes and other constants, generated from discuss sources
#
# NOTE: this file was autogenerated from the following files:

# Error codes
DUP_MTG_NAME = 32201984
BAD_PATH = 32201985
NO_ACCESS = 32201986
NO_SUCH_MTG = 32201987
NEW_VERSION = 32201988
INCONSISTENT = 32201989
BAD_MTG_NAME = 32201990
NO_SUCH_TRN = 32201991
DELETED_TRN = 32201992
NO_WRITE = 32201993
EXPUNGED_TRN = 32201994
TRN_NOT_DELETED = 32201995
CANNOT_REMOVE = 32201996
BAD_MODES = 32201997
NO_PRINC = 32201998
NO_MTGS_FILE = 32201999
BAD_MTGS_FILE = 32202000
YOU_TWIT = 32202001
NO_SUCH_USER = 32202002
CANT_WRITE_TEMP = 32202003
CANT_ATTEND = 32202004
NO_SUPPORT = 32202005
MTG_MOVED = 32202006

# Error code descriptions
errors = {
    DUP_MTG_NAME : "Meeting already exists",
    BAD_PATH : "A bad pathname was given",
    NO_ACCESS : "Insufficient access for operation",
    NO_SUCH_MTG : "Meeting does not exist",
    NEW_VERSION : "Invalid version number in meeting",
    INCONSISTENT : "There is an inconsistency in the meeting",
    BAD_MTG_NAME : "Invalid meeting name",
    NO_SUCH_TRN : "No such transaction",
    DELETED_TRN : "Transaction has been deleted",
    NO_WRITE : "Cannot write to transaction file",
    EXPUNGED_TRN : "Transaction has been expunged",
    TRN_NOT_DELETED : "Transaction is not deleted",
    CANNOT_REMOVE : "Cannot remove meeting",
    BAD_MODES : "Invalid mode for this access control list",
    NO_PRINC : "Principal not on access control list",
    NO_MTGS_FILE : "No '.meetings' file",
    BAD_MTGS_FILE : "Invalid format in meetings file",
    YOU_TWIT : "Chairman cannot remove his own access",
    NO_SUCH_USER : "No such user on this system",
    CANT_WRITE_TEMP : "Cannot write temporary file",
    CANT_ATTEND : "Insufficient access to attend meeting",
    NO_SUPPORT : "Server does not support this operation",
    MTG_MOVED : "The meeting has moved",
}

# Definitions from rpc.h
MAXARGS = 20
INTTYPE = 1
STRTYPE = 2
BOOLTYPE = 3
TFILETYPE = 4
ADD_TRN = 1
GET_TRN_INFO = 2
DELETE_TRN = 3
RETRIEVE_TRN = 4
CREATE_MTG = 5
OLD_GET_MTG_INFO = 6
START_MTG_INFO = 7
NEXT_MTG_INFO = 8
GET_TRN = 9
REMOVE_MTG = 10
UPDATED_MTG = 11
GET_MTG_INFO = 12
GET_ACL = 13
GET_ACCESS = 14
SET_ACCESS = 15
DELETE_ACCESS = 16
WHO_AM_I = 17
GET_TRN_INFO2 = 18
GET_SERVER_VERSION = 19
SET_TRN_FLAGS = 20
ADD_TRN2 = 21
GET_TRN_INFO3 = 22
REPLY_TYPE = 440
PROC_BASE = 400
TFILE_BLK = 500
KRB_TICKET = 501
UNKNOWN_CALL = 502
KRB_TICKET2 = 503
TICKET_REPLY = 504
SERVER_0 = 0
SERVER_1 = 1
SERVER_2 = 2
SERVER_3 = 3

